version: '3'

services:
    serverx:
        build: . # CHAMA O DOCKERFILE
        command: 'yarn start'
        environment:
            TZ: 'America/Sao_Paulo'
        expose:
            - 4000
        ports:
            - '4000:4000/tcp'
        restart: unless-stopped
        networks:
            - example-1
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 128M

networks:
    example-1:
